channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.6    # Python version 3.6
    - cython        # Python <-> C interfacing
    - cartopy       # Geographic plotting toolkit
    - dask          # Parallel processing library
    - jupyter       # Jupyter federation architecture
    - jupyterlab    # next-generation Jupyter
    - matplotlib    # 2D plotting library
    - netcdf4       # netcdf4 Python API, backend for xarray
    - scipy         # Common math/stats/science functions
    - scikit-learn  # Machine learning library
    - seaborn       # Statistical visualizations
    - xarray        # the major tool to work with NetCDF data
    - xbpch         # Interface for bpch output files
    - esmpy         # Python interface to ESMF (xesmf dependency)
    - pip:
        # These are additional libraries to search for on PyPI
        - xesmf    # Regridding xarray and numpy data